
import { Language, MarketData, OrderSide, Position, MarginMode, OrderType, AccountInfo, Order } from './types';

export const TIMEFRAMES = ['1m', '3m', '5m', '15m', '30m', '1H', '2H', '4H', '8H', '12H', '1D', '3D', '1W', '1M'];

export const CHART_DATA = Array.from({ length: 50 }, (_, i) => {
  const open = 2840 + Math.random() * 20;
  const close = 2840 + Math.random() * 20;
  return {
    time: i,
    open,
    high: Math.max(open, close) + Math.random() * 5,
    low: Math.min(open, close) - Math.random() * 5,
    close,
  };
});

export const TRANSLATIONS = {
  'en': {
    connectWallet: 'Connect Wallet',
    deposit: 'Deposit',
    withdraw: 'Withdraw',
    perp: 'Perp',
    lastPrice: 'Last Price',
    markPrice: 'Mark Price',
    indexPrice: 'Index Price',
    fundingRate: 'Funding / Countdown',
    change24h: '24h Change',
    highLow24h: '24h High / Low',
    volume24h: '24h Vol (XAU) / T.Over (USDC)',
    openInterest: 'Open Interest (USDC)',
    orderBook: 'Order Book',
    recentTrades: 'Recent Trades',
    price: 'Price',
    amount: 'Amount',
    total: 'Total',
    buyLong: 'Buy / Long',
    sellShort: 'Sell / Short',
    avail: 'Avail',
    market: 'Market',
    limit: 'Limit',
    leverage: 'Leverage',
    cross: 'Cross',
    isolated: 'Isolated',
    margin: 'Margin',
    cost: 'Cost',
    positions: 'Positions',
    openOrders: 'Open Orders',
    orderHistory: 'Order History',
    tradeHistory: 'Trade History',
    assetsHistory: 'Asset History',
    fundingHistory: 'Funding History',
    closeAll: 'Close All',
    cancelAll: 'Cancel All',
    symbol: 'Symbol',
    size: 'Size',
    entryPrice: 'Entry Price',
    liqPrice: 'Liq. Price',
    unrealizedPnl: 'Unrealized PnL / ROI',
    action: 'Action',
    addMargin: 'Add Margin',
    removeMargin: 'Extract Margin',
    confirm: 'Confirm',
    cancel: 'Cancel',
    success: 'Success',
    settings: 'Settings',
    language: 'Language',
    theme: 'Theme',
    contractAccount: 'Contract Account',
    totalValue: 'Total Value',
    unrealized: 'Unrealized PnL',
    usdcMargin: 'USDC Margin',
    marginRatio: 'Margin Ratio',
    maintMargin: 'Maint. Margin',
    marginBalance: 'Margin Balance',
    selectWallet: 'Select Wallet',
    signToLogin: 'Sign to Login',
    network: 'Network',
    max: 'Max',
    walletBalance: 'Wallet Avail',
    processing: 'Processing...',
    closePos: 'Close Position',
    tradingPair: 'Trading Pair',
    closePrice: 'Price',
    closeAmount: 'Amount',
    estPnl: 'Est. PnL',
    heldAmount: 'Holding Amount',
    long: 'Long',
    short: 'Short',
    nominalValue: 'Notional Value',
    accountBalance: 'Account Balance',
    viewOnExplorer: 'View on Explorer',
    disconnect: 'Disconnect',
    copied: 'Copied Success!',
    posMode: 'Position Mode',
    oneWay: 'One-way',
    hedge: 'Hedge',
    orderConfirm: 'Order Confirmation',
    popupNotify: 'Popup Notifications',
    emailNotify: 'Email Notifications',
    setEmail: 'Set Email',
    bindEmail: 'Bind Email',
    sendCode: 'Send Code',
    verifyCode: 'Verification Code',
    contract: 'Contract',
    availExtract: 'Available to Extract',
    depositTips: 'Tips: Arbitrum deposit time is 5~10 mins',
    withdrawFee: 'Withdrawal Fee',
    actualAmount: 'Actual Received',
    signatureReq: 'Signature Request',
    signMsg: 'To finalize login, please sign the message in your wallet.',
    signBtn: 'Sign and Login',
    type: 'Type',
    time: 'Time',
    all: 'All',
    tradingFee: 'Trading Fee',
    fundingFee: 'Funding Fee',
    realizedPnl: 'Realized PnL',
    liquidationFee: 'Liquidation Fee',
    maxOpen: 'Max Open',
    estFee: 'Est. Fee',
    filled: 'Filled',
    totalOrder: 'Total',
    fillRate: 'Fill %',
    status: 'Status',
    txHash: 'Tx Hash',
    fee: 'Fee',
    filledOrder: 'Filled',
    partialFilled: 'Partial',
    canceled: 'Canceled',
    expired: 'Expired',
    confirming: 'Confirming',
    completed: 'Completed',
    reviewing: 'Reviewing',
    rejected: 'Rejected',
    failed: 'Failed',
    marketLimitClose: 'Market/Limit Close',
    closeAllConfirm: 'Are you sure you want to close all active positions at market price?',
    assetHeader: 'Asset',
    marginRate: 'Margin Rate',
    adjustLeverage: 'Adjust Leverage',
    cancelOrder: 'Cancel',
    modifyEmail: 'Modify Email',
    fundingDetail: {
      interval: 'Interval',
      direction: 'Payment Direction',
      longPaysShort: 'Long pays Short',
      shortPaysLong: 'Short pays Long',
      estAPR: 'Est. Annualized (APR)'
    },
    explanations: {
      lastPrice: 'The Last Price is the most recent trade price of the contract, used for realized PnL, unaffected by index or mark price.',
      markPrice: 'Mark Price is used to trigger liquidation and calculate unrealized PnL, protecting against market manipulation.',
      indexPrice: 'Index Price is the weighted average price of the underlying asset across major exchanges.',
      fundingRate: 'Funding rates ensure the contract price stays anchored to the underlying spot price.',
      change24h: 'The absolute and percentage price movement over the last 24 hours.',
      highLow24h: 'The highest and lowest trade prices recorded in the last 24 hours.',
      volume24h: 'The total number of contracts (XAU) and total value (USDC) traded in the last 24 hours.',
      openInterest: 'The total value of all currently outstanding (unclosed) contracts in the market.',
      totalValue: 'The sum of your wallet balance and all unrealized profits or losses.',
      unrealized: 'The total current profit or loss of all your open positions based on the mark price.',
      marginRatio: 'Calculated as (Maintenance Margin / Margin Balance). Liquidation occurs if this reaches 100%.',
      maintMargin: 'The minimum amount of equity required to keep your positions open.',
      marginBalance: 'The total equity in your account (Balance + Unrealized PnL) available to cover margin.',
      nominalValue: 'The total value of the position calculated as Size * Mark Price.',
      entryPrice: 'The average price at which the position was opened.',
      liqPrice: 'The price at which the position will trigger mandatory liquidation.',
      margin: 'The collateral amount currently locked to support this position.',
      unrealizedPnl: 'Current floating profit or loss for the position and the percentage Return on Investment.'
    }
  },
  'zh-CN': {
    connectWallet: '连接钱包',
    deposit: '充值',
    withdraw: '提现',
    perp: '永续合约',
    lastPrice: '最新价格',
    markPrice: '标记价格',
    indexPrice: '指数价格',
    fundingRate: '资金费率 / 倒计时',
    change24h: '24h涨跌额 / 涨跌幅',
    highLow24h: '24h最高价 / 最低价',
    volume24h: '24h成交量(XAU) / 成交额(USDC)',
    openInterest: '未平仓合约(USDC)',
    orderBook: '订单薄',
    recentTrades: '最新成交',
    price: '价格',
    amount: '数量',
    total: '总额',
    buyLong: '买入 / 做多',
    sellShort: '卖出 / 做空',
    avail: '可用',
    market: '市价',
    limit: '限价',
    leverage: '杠杆',
    cross: '全仓',
    isolated: '逐仓',
    margin: '保证金',
    cost: '预估费用',
    positions: '仓位',
    openOrders: '当前委托',
    orderHistory: '历史委托',
    tradeHistory: '历史成交',
    assetsHistory: '充提记录',
    fundingHistory: '资金记录',
    closeAll: '市价全平',
    cancelAll: '全部取消',
    symbol: '合约',
    size: '持仓量',
    entryPrice: '开仓价格',
    liqPrice: '清算价格',
    unrealizedPnl: '未实现盈亏 / 回报率',
    action: '操作',
    addMargin: '增加保证金',
    removeMargin: '提取保证金',
    confirm: '确认',
    cancel: '取消',
    success: '成功',
    settings: '设置',
    language: '语言',
    theme: '主题',
    contractAccount: '合约账户',
    totalValue: '持仓总价值',
    unrealized: '未实现盈亏',
    usdcMargin: 'USDC 全仓保证金',
    marginRatio: '保证金比率',
    maintMargin: '维持保证金',
    marginBalance: '保证金余额',
    selectWallet: '选择钱包',
    signToLogin: '签名登录',
    network: '网络',
    max: '最大',
    walletBalance: '钱包可用',
    processing: '处理中...',
    closePos: '平仓',
    tradingPair: '交易对',
    closePrice: '价格',
    closeAmount: '数量',
    estPnl: '预估盈亏',
    heldAmount: '持仓数量',
    long: '多头',
    short: '空头',
    nominalValue: '名义价值',
    accountBalance: '账户余额',
    viewOnExplorer: '在浏览器中查看',
    disconnect: '断开连接',
    copied: '复制成功',
    posMode: '持仓模式切换',
    oneWay: '单向',
    hedge: '双向',
    orderConfirm: '订单确认开关',
    popupNotify: '弹出通知开关',
    emailNotify: '邮箱通知开关',
    setEmail: '设置邮箱',
    bindEmail: '绑定邮箱',
    sendCode: '发送验证码',
    verifyCode: '验证码',
    contract: '合约',
    availExtract: '可提取',
    depositTips: 'Tips: Arbitrum的预计存款时间为5~10分钟',
    withdrawFee: '提现手续费',
    actualAmount: '实际到账',
    signatureReq: '签名请求',
    signMsg: '为了完成登录流程，请在钱包中签署该消息。',
    signBtn: '签名并登录',
    type: '类型',
    time: '时间',
    all: '全部',
    tradingFee: '交易费',
    fundingFee: '资金费',
    realizedPnl: '已实现盈亏',
    liquidationFee: '清算费',
    maxOpen: '可开',
    estFee: '预估费用',
    filled: '成交数量',
    totalOrder: '总量',
    fillRate: '成交率',
    status: '状态',
    txHash: '交易 hash',
    fee: '手续费',
    filledOrder: '已成交',
    partialFilled: '部分成交',
    canceled: '已取消',
    expired: '已过期',
    confirming: '确认中',
    completed: '已完成',
    reviewing: '审核中',
    rejected: '已拒绝',
    failed: '已失败',
    marketLimitClose: '市价/限价平仓',
    closeAllConfirm: '您确定要以市价清空全部持仓吗？',
    assetHeader: '资产符号',
    marginRate: '保证金比率',
    adjustLeverage: '杠杆调整',
    cancelOrder: '取消',
    modifyEmail: '修改邮箱',
    fundingDetail: {
      interval: '收费间隔',
      direction: '支付方向',
      longPaysShort: '多头 pays 空头',
      shortPaysLong: '空头 pays 多头',
      estAPR: '预估年化 (APR)'
    },
    explanations: {
      lastPrice: '最新价格是合约最近一笔成交价格，用于计算已实现的盈亏，不受指数价格和标记价格影响。',
      markPrice: '标记价格是用于计算未实现盈亏和触发强平的价格，旨在防止市场操纵和不必要的爆仓。',
      indexPrice: '指数价格是由多家主流交易所的现货价格加权计算而成，反映了资产的真实市场价格。',
      fundingRate: '资金费率旨在使永续合约价格锚定现货价格，通过多空双方互相支付费用来实现。',
      change24h: '过去 24 小时内价格的涨跌绝对值以及涨跌百分比。',
      highLow24h: '过去 24 小时内的最高成交价和最低成交价。',
      volume24h: '过去 24 小时内成交的总合约数量和对应的名义价值（USDC）。',
      openInterest: '当前市场上所有未平仓的合约总持仓量名义价值。',
      totalValue: '持仓总价值是您账户中所有资产的总和，包含钱包余额和当前所有未实现盈亏。',
      unrealized: '未实现盈亏是基于标记价格计算的当前所有持仓的浮动盈利或亏损。',
      marginRatio: '保证金比率 = (维持保证金 / 保证金余额) * 100%。当该比例达到 100% 时，将触发强制平仓。',
      maintMargin: '维持当前仓位所需的最低保证金金额。',
      marginBalance: '账户中可用于支持仓位的总权益（账户余额 + 未实现盈亏）。',
      nominalValue: '名义价值 = 持仓量 * 标记价格，代表了当前仓位的总市场敞口。',
      entryPrice: '该仓位开仓时的加权平均价格。',
      liqPrice: '当标记价格触及此价格时，该仓位将被系统强制接管并平仓。',
      margin: '当前仓位锁定的本金部分，用于承担潜在亏损。',
      unrealizedPnl: '当前持仓的浮动盈利或亏损，以及对应本金的回报率（ROI）。'
    }
  },
  'zh-TW': {
    connectWallet: '連接錢包',
    deposit: '充值',
    withdraw: '提現',
    perp: '永續合約',
    lastPrice: '最新價格',
    markPrice: '標記價格',
    indexPrice: '指數價格',
    fundingRate: '資金費率 / 倒計時',
    change24h: '24h漲跌額 / 漲跌幅',
    highLow24h: '24h最高價 / 最低價',
    volume24h: '24h成交量(XAU) / 成交額(USDC)',
    openInterest: '未平倉合約(USDC)',
    orderBook: '訂單簿',
    recentTrades: '最新成交',
    price: '價格',
    amount: '數量',
    total: '總額',
    buyLong: '買入 / 做多',
    sellShort: '賣出 / 做空',
    avail: '可用',
    market: '市價',
    limit: '限價',
    leverage: '槓桿',
    cross: '全倉',
    isolated: '逐倉',
    margin: '保證金',
    cost: '預估費用',
    positions: '倉位',
    openOrders: '當前委託',
    orderHistory: '歷史委託',
    tradeHistory: '歷史成交',
    assetsHistory: '充提記錄',
    fundingHistory: '資金記錄',
    closeAll: '市價全平',
    cancelAll: '全部取消',
    symbol: '合約',
    size: '持倉量',
    entryPrice: '開倉價格',
    liqPrice: '清算價格',
    unrealizedPnl: '未實現盈虧 / 回報率',
    action: '操作',
    addMargin: '增加保證金',
    removeMargin: '提取保證金',
    confirm: '確認',
    cancel: '取消',
    success: '成功',
    settings: '設置',
    language: '語言',
    theme: '主題',
    contractAccount: '合約賬戶',
    totalValue: '持倉總價值',
    unrealized: '未實現盈虧',
    usdcMargin: 'USDC 全倉保證金',
    marginRatio: '保證金比率',
    maintMargin: '維持保證金',
    marginBalance: '保證金餘額',
    selectWallet: '選擇錢包',
    signToLogin: '簽名登錄',
    network: '網絡',
    max: '最大',
    walletBalance: '錢包可用',
    processing: '處理中...',
    closePos: '平倉',
    tradingPair: '交易對',
    closePrice: '價格',
    closeAmount: '數量',
    estPnl: '預估盈虧',
    heldAmount: '持倉數量',
    long: '多頭',
    short: '空頭',
    nominalValue: '名義價值',
    accountBalance: '賬戶餘額',
    viewOnExplorer: '在瀏覽器中查看',
    disconnect: '斷開連接',
    copied: '複製成功',
    posMode: '持倉模式切換',
    oneWay: '單向持倉模式',
    hedge: '雙向持倉模式',
    orderConfirm: '訂單確認開關',
    popupNotify: '彈出通知開關',
    emailNotify: '郵箱通知開關',
    setEmail: '設置郵箱',
    bindEmail: '綁定郵箱',
    sendCode: '發送驗證碼',
    verifyCode: '驗證碼',
    contract: '合約',
    availExtract: '可提取',
    depositTips: 'Tips: Arbitrum的預計存款時間為5~10分鐘',
    withdrawFee: '提現手續費',
    actualAmount: '實際到賬',
    signatureReq: '簽名請求',
    signMsg: '為了完成登錄流程，請在錢包中簽署該消息。',
    signBtn: '簽名並登錄',
    type: '類型',
    time: '時間',
    all: '全部',
    tradingFee: '交易費',
    fundingFee: '資金費',
    realizedPnl: '已實現盈虧',
    liquidationFee: '清算費',
    maxOpen: '可開',
    estFee: '預估費用',
    filled: '成交數量',
    totalOrder: '总量',
    fillRate: '成交率',
    status: '狀態',
    txHash: '交易 hash',
    fee: '手續費',
    filledOrder: '已成交',
    partialFilled: '部分成交',
    canceled: '已取消',
    expired: '已過期',
    confirming: '確認中',
    completed: '已完成',
    reviewing: '審核中',
    rejected: '已拒絕',
    failed: '已失敗',
    marketLimitClose: '市價/限價平倉',
    closeAllConfirm: '您確定要以市價清空全部持倉嗎？',
    assetHeader: '資產符號',
    marginRate: '保證金比率',
    adjustLeverage: '槓桿調整',
    cancelOrder: '取消',
    modifyEmail: '修改郵箱',
    fundingDetail: {
      interval: '收費間隔',
      direction: '支付方向',
      longPaysShort: '多頭 pays 空頭',
      shortPaysLong: '空頭 pays 多頭',
      estAPR: '預估年化 (APR)'
    },
    explanations: {
      lastPrice: '最新價格是合約最近一筆成交價格，用於計算已實現的盈虧，不受指數價格和標記價格影響。',
      markPrice: '標記價格是用於計算未實現盈虧和觸發強平的價格，旨在防止市場操縱和不必要的爆倉。',
      indexPrice: '指數價格是由多家主流交易所的現貨價格加權計算而成，反映了資產的真實市場價格。',
      fundingRate: '資金費率旨在使永續合約價格錨定現貨價格，通過多空雙方互相支付費用來實現。',
      change24h: '過去 24 小時內價格的漲跌絕對值以及漲跌百分比。',
      highLow24h: '過去 24 小時內的最高成交價和最低成交價。',
      volume24h: '過去 24 小時內成交的總合約數量和對應的名義價值（USDC）。',
      openInterest: '當前市場上所有未平倉的合約總持倉量名義價值。',
      totalValue: '持倉總價值是您賬戶中所有資產的總和，包含錢包餘額和當前所有未實現盈虧。',
      unrealized: '未實現盈虧是基於標記價格計算的當前所有持倉的浮動盈利或虧損。',
      marginRatio: '保證金比率 = (維持保證金 / 保證金餘額) * 100%。當該比例達到 100% 時，將觸發強制平倉。',
      maintMargin: '維持當前倉位所需的最低保證金金額。',
      marginBalance: '賬戶中可用於支持倉位的總權益（賬戶餘額 + 未實現盈虧）。',
      nominalValue: '名義價值 = 持倉量 * 標記價格，代表了當前倉位的總市場敞口。',
      entryPrice: '該倉位開倉時的加權平均價格。',
      liqPrice: '當標記價格觸及此價格時，該倉位將被系統強制接管並平倉。',
      margin: '當前倉位鎖定的本金部分，用於承擔潛在虧損。',
      unrealizedPnl: '當前持倉的浮動盈利或虧損，以及對應本金的回報率（ROI）。'
    }
  }
};

export const INITIAL_MARKET_DATA: MarketData = {
  symbol: 'XAUUSDC',
  lastPrice: 2845.63,
  markPrice: 2845.63,
  indexPrice: 2845.63,
  change24h: 34,
  change24hPercent: 1.21,
  high24h: 2854.63,
  low24h: 2824.63,
  volume24h: 234.32,
  turnover24h: 13338233.34,
  openInterest: 13338233.34,
  fundingRate: 0.0034,
  nextFundingTime: Date.now() + 1000 * 60 * 56, // 56 mins
};

export const MOCK_POSITIONS: Position[] = [
  {
    id: '1',
    symbol: 'XAUUSDC',
    side: OrderSide.BUY,
    size: 1.23,
    entryPrice: 2829.32,
    markPrice: 2845.63,
    leverage: 2,
    margin: 1562.43,
    marginMode: MarginMode.ISOLATED,
    pnl: 2234.23,
    pnlPercent: 15.23,
    liquidationPrice: 2154.58
  }
];

export const MOCK_FUNDING_RECORDS = [
  { id: '1', time: '2024-03-20 14:00:00', type: 'tradingFee', amount: -0.52, symbol: 'XAUUSDC' },
  { id: '2', time: '2024-03-20 12:00:00', type: 'fundingFee', amount: 1.25, symbol: 'XAUUSDC' },
  { id: '3', time: '2024-03-20 10:00:00', type: 'realizedPnl', amount: 154.20, symbol: 'XAUUSDC' },
  { id: '4', time: '2024-03-19 22:00:00', type: 'tradingFee', amount: -0.48, symbol: 'XAUUSDC' },
  { id: '5', time: '2024-03-19 16:00:00', type: 'liquidationFee', amount: -12.00, symbol: 'XAUUSDC' },
];

export const MOCK_HISTORY_ORDERS = [
  { id: 'h1', symbol: 'XAUUSDC', side: 'BUY', type: 'LIMIT', price: 2820.50, filled: 1.5, total: 1.5, status: 'filledOrder', time: '2024-03-20 13:45:12' },
  { id: 'h2', symbol: 'XAUUSDC', side: 'SELL', type: 'LIMIT', price: 2850.00, filled: 0.5, total: 1.0, status: 'partialFilled', time: '2024-03-20 12:30:05' },
  { id: 'h3', symbol: 'XAUUSDC', side: 'BUY', type: 'LIMIT', price: 2800.00, filled: 0, total: 2.0, status: 'canceled', time: '2024-03-20 11:15:40' },
  { id: 'h4', symbol: 'XAUUSDC', side: 'SELL', type: 'MARKET', price: 2840.20, filled: 0, total: 0.5, status: 'expired', time: '2024-03-20 10:00:00' },
];

export const MOCK_TRADE_HISTORY = [
  { id: 't1', symbol: 'XAUUSDC', side: 'BUY', price: 2845.10, amount: 0.8, total: 2276.08, fee: 1.13, pnl: 45.20, time: '2024-03-20 14:10:22' },
  { id: 't2', symbol: 'XAUUSDC', side: 'BUY', price: 2845.05, amount: 0.4, total: 1138.02, fee: 0.57, pnl: 22.10, time: '2024-03-20 14:10:22' },
  { id: 't3', symbol: 'XAUUSDC', side: 'SELL', price: 2838.40, amount: 1.2, total: 3406.08, fee: 1.70, pnl: -12.40, time: '2024-03-20 09:20:15' },
];

export const MOCK_ASSETS_HISTORY = [
  { id: 'a1', asset: 'USDC', type: 'deposit', amount: 5000, fee: null, hash: '0x7b...3f2a', status: 'completed', time: '2024-03-20 08:00:00' },
  { id: 'a2', asset: 'USDC', type: 'withdraw', amount: 1000, fee: 0.5, hash: '0xa4...1d9e', status: 'processing', time: '2024-03-20 15:20:00' },
  { id: 'a3', asset: 'USDC', type: 'deposit', amount: 200, fee: null, hash: '0x1c...9b8c', status: 'confirming', time: '2024-03-20 16:45:00' },
  { id: 'a4', asset: 'USDC', type: 'withdraw', amount: 500, fee: 0.5, hash: '0xf2...e4a1', status: 'reviewing', time: '2024-03-19 14:00:00' },
  { id: 'a5', asset: 'USDC', type: 'withdraw', amount: 2000, fee: 0.5, hash: '0x8d...c3b2', status: 'rejected', time: '2024-03-18 10:30:00' },
];

export const MOCK_ASKS = Array.from({ length: 8 }, (_, i) => ({
  price: 2846.60 + (i * 0.4),
  amount: (Math.random() * 20).toFixed(3),
  total: (Math.random() * 50).toFixed(3)
})).reverse();

export const MOCK_BIDS = Array.from({ length: 8 }, (_, i) => ({
  price: 2844.45 - (i * 0.4),
  amount: (Math.random() * 20).toFixed(3),
  total: (Math.random() * 50).toFixed(3)
}));

export const INITIAL_ACCOUNT_INFO: AccountInfo = {
  totalValue: 12500.43,
  unrealizedPnl: 2010.00,
  marginRatio: 15.4,
  maintenanceMargin: 1200.00,
  marginBalance: 8000.43,
  walletBalance: 25000.00
};
